name: Makefile Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make
    - name: Build via Makefile
      run: make
    - name: Test
      run: |
        ./dmitree --help
        ./dmitree -d .
